/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amrit
 */
package com.mycompany.mavenproject2;
import java.awt.Color;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
public class AuthorFrame extends javax.swing.JFrame {
    private JTextField authorIdField, authorNameField;
    private JButton submitButton, backButton, searchButton;
    /**
     * Creates new form AuthorFrame
     */
    public AuthorFrame() {
        initComponentsAuthor();
    }
     private void initComponentsAuthor() {
        setTitle("New Author");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        getContentPane().setBackground(new Color(245, 245, 220));

        JLabel authorIdLabel = new JLabel("Author ID:");
        authorIdLabel.setBounds(10, 10, 100, 25);
        add(authorIdLabel);

        authorIdField = new JTextField();
        authorIdField.setBounds(120, 10, 160, 25);
        add(authorIdField);

        JLabel authorNameLabel = new JLabel("Author Name:");
        authorNameLabel.setBounds(10, 40, 100, 25);
        add(authorNameLabel);

        authorNameField = new JTextField();
        authorNameField.setBounds(120, 40, 160, 25);
        add(authorNameField);

        submitButton = new JButton("Submit");
        submitButton.setBounds(120, 80, 100, 25);
        add(submitButton);

        backButton = new JButton("Back to Main Menu");
        backButton.setBounds(230, 80, 150, 25);
        add(backButton);

        searchButton = new JButton("Search");
        searchButton.setBounds(290, 40, 90, 25);
        add(searchButton);



        // Action listener for submitButton
        submitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String authorId = authorIdField.getText();
                String authorName = authorNameField.getText();

                try (Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
                     PreparedStatement ps = conn.prepareStatement("INSERT INTO authors (author_id, author_name) VALUES (?, ?)")) {
                    ps.setString(1, authorId);
                    ps.setString(2, authorName);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Author added successfully!");
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error adding author: ");
                }
            }
        });

        // Action listener for backButton
        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new MainFrame().setVisible(true);
                dispose();
            }
        });

        // Action listener for searchButton
        searchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String authorIdToSearch = authorIdField.getText();

                try (Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
                     CallableStatement cs = conn.prepareCall("{call get_author_details(?, ?)}")) {
                    cs.setString(1, authorIdToSearch);
                    cs.registerOutParameter(2, java.sql.Types.VARCHAR);
                    cs.execute();

                    // Retrieve results
                    String authorName = cs.getString(2);

                    // Set retrieved values to text fields
                    authorNameField.setText(authorName);

                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error retrieving author details: ");
                }
            }
        });

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
