/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amrit
 */
package com.mycompany.mavenproject2;
import java.awt.Color;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
public class BookFrame extends javax.swing.JFrame {

    private JTextField bookIdField, bookNameField, authorIdField, publisherIdField, genreField;
    private JButton submitButton, backButton;
    
    public BookFrame() {
        initComponentsBook();
    }
    private void initComponentsBook() {
        setTitle("New Book");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        getContentPane().setBackground(new Color(245,245,220));

        JLabel bookIdLabel = new JLabel("Book ID:");
        bookIdLabel.setBounds(10, 10, 100, 25);
        add(bookIdLabel);

        bookIdField = new JTextField();
        bookIdField.setBounds(120, 10, 160, 25);
        add(bookIdField);

        JLabel bookNameLabel = new JLabel("Book Name:");
        bookNameLabel.setBounds(10, 40, 100, 25);
        add(bookNameLabel);

        bookNameField = new JTextField();
        bookNameField.setBounds(120, 40, 160, 25);
        add(bookNameField);

        JLabel authorIdLabel = new JLabel("Author ID:");
        authorIdLabel.setBounds(10, 70, 100, 25);
        add(authorIdLabel);

        authorIdField = new JTextField();
        authorIdField.setBounds(120, 70, 160, 25);
        add(authorIdField);

        JLabel publisherIdLabel = new JLabel("Publisher ID:");
        publisherIdLabel.setBounds(10, 100, 100, 25);
        add(publisherIdLabel);

        publisherIdField = new JTextField();
        publisherIdField.setBounds(120, 100, 160, 25);
        add(publisherIdField);

        JLabel genreLabel = new JLabel("Genre:");
        genreLabel.setBounds(10, 130, 100, 25);
        add(genreLabel);

        genreField = new JTextField();
        genreField.setBounds(120, 130, 160, 25);
        add(genreField);

        submitButton = new JButton("Submit");
        submitButton.setBounds(120, 170, 100, 25);
        add(submitButton);

        backButton = new JButton("Back to Main Menu");
        backButton.setBounds(230, 170, 150, 25);
        add(backButton);

        submitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String bookId = bookIdField.getText();
                String bookName = bookNameField.getText();
                String publisherId = publisherIdField.getText();
                String genre = genreField.getText();
                String authorIdsStr = authorIdField.getText();
                String[] authorIds = authorIdsStr.split(",");

                try (Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
                     PreparedStatement psBook = conn.prepareStatement("INSERT INTO books (book_id, book_name, publisher_id, genre) VALUES (?, ?, ?, ?)");
                     PreparedStatement psBookAuthor = conn.prepareStatement("INSERT INTO book_authors (book_id, author_id) VALUES (?, ?)")) {

                    // Insert into books table
                    psBook.setString(1, bookId);
                    psBook.setString(2, bookName);
                    psBook.setString(3, publisherId);
                    psBook.setString(4, genre);
                    psBook.executeUpdate();

                    // Insert into book_authors table
                    for (var authorId : authorIds) {
                        psBookAuthor.setString(1, bookId);
                        psBookAuthor.setString(2, authorId.trim());
                        psBookAuthor.executeUpdate();
                    }

                    JOptionPane.showMessageDialog(null, "Book added successfully!");
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error adding book: ");
                }
            }
        });

        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                new MainFrame().setVisible(true);
            }
        });

        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
