/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amrit
 */
package com.mycompany.mavenproject2;
import java.awt.Color;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
public class PublisherFrame extends javax.swing.JFrame {
    private JTextField publisherIdField, publisherNameField;
    private JButton submitButton, backButton, searchButton;
    /**
     * Creates new form PublisherFrame
     */
    public PublisherFrame() {
        initComponentsPublisher();
    }
    private void initComponentsPublisher() {
        setTitle("New Publisher");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        getContentPane().setBackground(new Color(245, 245, 220));

        JLabel publisherIdLabel = new JLabel("Publisher ID:");
        publisherIdLabel.setBounds(10, 10, 100, 25);
        add(publisherIdLabel);

        publisherIdField = new JTextField();
        publisherIdField.setBounds(120, 10, 160, 25);
        add(publisherIdField);

        JLabel publisherNameLabel = new JLabel("Publisher Name:");
        publisherNameLabel.setBounds(10, 40, 100, 25);
        add(publisherNameLabel);

        publisherNameField = new JTextField();
        publisherNameField.setBounds(120, 40, 160, 25);
        add(publisherNameField);

        submitButton = new JButton("Submit");
        submitButton.setBounds(120, 80, 100, 25);
        add(submitButton);

        backButton = new JButton("Back to Main Menu");
        backButton.setBounds(230, 80, 150, 25);
        add(backButton);

        searchButton = new JButton("Search");
        searchButton.setBounds(290, 120, 90, 25);
        add(searchButton);

        submitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String publisherId = publisherIdField.getText();
                String publisherName = publisherNameField.getText();

                try (Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
                     PreparedStatement ps = conn.prepareStatement("INSERT INTO publishers (publisher_id, publisher_name) VALUES (?, ?)")) {
                    ps.setString(1, publisherId);
                    ps.setString(2, publisherName);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Publisher added successfully!");
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error adding publisher: " + ex.getMessage());
                }
            }
        });

        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new MainFrame().setVisible(true);
                dispose();
            }
        });

        searchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String publisherIdToSearch = publisherIdField.getText();

                try (Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
                     PreparedStatement ps = conn.prepareStatement("SELECT publisher_name FROM publishers WHERE publisher_id = ?")) {
                    ps.setString(1, publisherIdToSearch);
                    ResultSet rs = ps.executeQuery();

                    if (rs.next()) {
                        String publisherName = rs.getString("publisher_name");
                        publisherNameField.setText(publisherName);
                    } else {
                        JOptionPane.showMessageDialog(null, "Publisher ID not found!");
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error searching publisher: " + ex.getMessage());
                }
            }
        });

        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublisherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublisherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublisherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublisherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublisherFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
